### ISSUE TITLE
deployNodes is broken due to the switch to X.500 names

### ISSUE THREAD

**Issue by mikehearn** [corda/cordapp-template#82]
```
--- Corda Open Source 0.12-SNAPSHOT (a22d8ed) -----------------------------------------------

📚  New! Training now available worldwide, see https://corda.net/corda-training/

Logs can be found in                    : /Users/mike/Source/R3/playground/event-bookings/eventbookings/build/nodes/Controller/logs
Exception in thread "main" java.lang.IllegalArgumentException: badly formatted directory string
	at org.bouncycastle.asn1.x500.style.IETFUtils.rDNsFromString(Unknown Source)
	at org.bouncycastle.asn1.x500.style.BCStyle.fromString(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at org.bouncycastle.asn1.x500.X500Name.<init>(Unknown Source)
	at net.corda.nodeapi.config.ConfigUtilitiesKt.getSingleValue(ConfigUtilities.kt:74)
	at net.corda.nodeapi.config.ConfigUtilitiesKt.getValueInternal(ConfigUtilities.kt:56)
	at net.corda.nodeapi.config.ConfigUtilitiesKt.parseAs(ConfigUtilities.kt:40)
	at net.corda.node.CmdLineOptions.loadConfig(ArgsParser.kt:73)
	at net.corda.node.Corda.main(Corda.kt:105)
```

**Comment by joeldudleyr3** [comment]
Fixed.
